<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address type HomeOffice_dob</name>
   <tag></tag>
   <elementGuidId>2f322888-8e66-40c6-8a9b-63f4e19523f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datepicker']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#datepicker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09065a7c-d218-4db6-8be5-b089e4d15209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4d56f5e-99bb-4900-aded-8c0f7e54f16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>780870f4-e0f0-4111-864c-3b4619573451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dob</value>
      <webElementGuid>f0f8052f-252d-4d83-8b06-55e957ecceca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Date of birth</value>
      <webElementGuid>6226b29e-52d1-4b60-92ae-070093190f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hasDatepicker</value>
      <webElementGuid>d2596bae-24eb-41ad-8e62-13a9c259c44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker&quot;)</value>
      <webElementGuid>19365e53-4577-452b-abe1-41b0044fcb94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datepicker']</value>
      <webElementGuid>9a544439-57cc-48e9-8ce1-a9041d48ba8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-content1']/form/input[6]</value>
      <webElementGuid>ceda72d2-b3fc-4909-9a8d-7062999d317f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>3e4aa0fe-6eea-4f35-832c-23281203a60a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'datepicker' and @name = 'dob' and @placeholder = 'Date of birth']</value>
      <webElementGuid>85289200-d862-471a-867d-3d8c8a664af7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
