<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address type HomeOffice_phone</name>
   <tag></tag>
   <elementGuidId>2488366e-255a-44f9-8a1d-abb9bbaa9fe4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;phone&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1f85afa-17ff-4cf6-9762-a7b60ca73607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87661f42-d339-4b5c-b58d-febae50d4fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone</value>
      <webElementGuid>05167a1e-109d-4fee-9302-5a96c6911621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>b3e8b219-a9d7-4f1a-b192-e3f116dc8fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-content1&quot;)/form[1]/input[7]</value>
      <webElementGuid>7bd34501-1aa5-4c8c-95a1-622c899766f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='phone']</value>
      <webElementGuid>e5e41de5-4a54-4623-83da-cb08b07fd1ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-content1']/form/input[7]</value>
      <webElementGuid>78c6ee97-fef5-4a81-9de2-4b89157b63e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[7]</value>
      <webElementGuid>0533f8c3-0bc1-45aa-9f90-2ee5aa434734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Phone' and @name = 'phone']</value>
      <webElementGuid>8c6677a4-798b-4cab-a076-9ab4714d9a6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
